# Generated by Django 3.2 on 2022-12-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('card_number', models.CharField(max_length=16, unique=True, verbose_name='Номер карты')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование блюда')),
                ('start_price', models.IntegerField(verbose_name='Начальная стоимость блюда')),
                ('type_of_cuisine', models.CharField(max_length=50, verbose_name='Тип кухни')),
                ('calories', models.IntegerField(verbose_name='Количество калорий')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ингредиента')),
                ('extra_price', models.IntegerField(verbose_name='Стоимость надбавки')),
                ('calories', models.IntegerField(verbose_name='Количество калорий')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=40, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KFC.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('vegetarian', models.BooleanField(default=False)),
                ('food_status', models.CharField(default='Перекус', max_length=50, verbose_name='Тип блюда')),
                ('final_price', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='KFC.client')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KFC.food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KFC.ingredient')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='KFC.worker')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KFC.user'),
        ),
        migrations.CreateModel(
            name='Order_full',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('KFC.order',),
        ),
    ]
